version: '3'
services:
  accounting-api:
    container_name: accounting-container
    image: pblpnt/accounting-api:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_PASSWORD=PabloM17$
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432
      - DATABASE_USERNAME=postgres
      - ACTIVE_PROFILE=prod


