server:
  servlet:
    context-path: /accounting
  port: 5000

spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: accounting-api
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: ${DATABASE_URL}/accounting_dev
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      default-media-type: application/json


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}/accounting_prod
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    rest:
      default-media-type: application/json